version: '3'
services:
  spark-master:
    container_name: spark-master
    image: 'bitnami/spark:3.3.1'
    environment:
      - SPARK_MODE=master
      - SPARK_PORT=7077
      - SPARK_JUPYTER_ENABLED=yes
      - SPARK_JUPYTER_PORT=9001
    ports:
      - '7077:7077'
      - '8080:8080'
      - '9001:9001'
  spark-worker:
    container_name: spark-worker-1
    image: 'bitnami/spark:3.3.1'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - '8081:8081'
    depends_on:
      - spark-master
  spark-worker2:
    container_name: spark-worker-2
    image: 'bitnami/spark:3.3.1'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - '8082:8082'
    depends_on:
      - spark-master
  jupyter:
    container_name: jupyter-notebook
    image: 'jupyter/pyspark-notebook:spark-3.3.1'
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_JUPYTER_ENABLED=yes
      - SPARK_JUPYTER_PORT=9001
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=mypassword
    ports:
      - '8888:8888'
      - '4040:4040'
    volumes:
      - './notebooks:/home/jovyan/work'
    depends_on:
      - spark-master
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

